version: '3.8'
services:
  identity-api:
    image: jonathan31amaral/identity-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - identity-network
  database:
    image: postgres
    env_file:
      - database.env
    volumes:
      - /:/var/lib/postgresql/data/
    networks:
      - identity-network

networks:
  identity-network:
    driver: bridge
